#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/zookeeper-server" ]; then
	invoke-rc.d zookeeper-server stop || exit 1
fi
# End automatically added section
